name: Dependency Review

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner (audit)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - name: Checkout PR
        uses: actions/checkout@v4

      - name: Dependency Review
        if: ${{ github.event.pull_request.head.repo.fork == false }}
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          allow-licenses: MIT,Apache-2.0,BSD-2-Clause,BSD-3-Clause
          comment-summary-in-pr: true
